### ISSUE TITLE
Give more users the option to add players to a match

### ISSUE THREAD

**Issue by mcepok** [teheru/nczone#10]
* We already have a replace function at controller/api.php -> add_pair_preview() and similar
* Currently there is a single mod permission acl::m_zone_change_match in order to do this
* We need another user permission acl::u_zone_change_match (or something) for normal users in order to be able to add other users under certain conditions
* For now, this condition should be, that the user drawed that match

**Comment by Des-** [comment]
We already have acl::u_zone_change_match. What is it currently doing?
