### ISSUE TITLE
Any guide for setting this up with another team?

### ISSUE THREAD

**Issue by Sam152** [teheru/nczone#57]
Looking for some general docs on getting this going for Straya. I managed to get an installation working, but was a bit of a loss on how to configure this correctly.

**Comment by mcepok** [comment]
Sure, I will write a small guide how to get a basic setup similar to the one we currently use today in the evening.

**Comment by Sam152** [comment]
Thanks @mcepok! :)

**Comment by mcepok** [comment]
I updated the [README](README.md). Let me know if you're missing anything.

**Comment by Sam152** [comment]
Thank you, this was immensely helpful.

**Comment by mcepok** [comment]
Out of curiosity - where are you hosting your Zone?

**Comment by Zutatensuppe** [comment]
Probably somewhere in Australia Kappa :P
