### ISSUE TITLE
Support PHPBB 3.3

### ISSUE THREAD

**Issue by Sam152** [teheru/nczone#64]
The only error I found when upgrading to 3.3 was the following:

>  TypeError: Return value of eru\nczone\utility\phpbb_util::container() must be an instance of Symfony\Component\DependencyInjection\ContainerBuilder, instance of phpbb_cache_container returned 

Removing the typehint made the extension work. We could also hint phpbb_cache_container, however that would mean it wouldn't work on 3.2.

**Comment by Sam152** [comment]
PR here: #65

**Comment by mcepok** [comment]
Merged, thanks!
